import fs from 'node:fs';
import {prepareRedirects} from './routes.mjs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import crypto from 'node:crypto';
export const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const j=s=>JSON.stringify(s).replace(/</g,'\\u003c');
export function build(){
const pub=path.join(root,'public'), dir=path.join(root,'content');
const site=JSON.parse(fs.readFileSync(path.join(dir,'site.json'),'utf8'));
const redirects=prepareRedirects(JSON.parse(fs.readFileSync(path.join(dir,'redirects.json'),'utf8')));
const pages=fs.readdirSync(dir).filter(x=>x.endsWith('.json')&&!['site.json','redirects.json'].includes(x)).map(x=>({slug:x.slice(0,-5),...JSON.parse(fs.readFileSync(path.join(dir,x),'utf8'))}));
for(const p of pages)for(const key of ['lastModified','datePublished'])if(p[key]&&(!/^\d{4}-\d{2}-\d{2}$/.test(p[key])||!Number.isFinite(Date.parse(p[key]))||new Date(p[key]).toISOString().slice(0,10)!==p[key]))throw Error('Ongeldige datum: '+p.slug+' '+key);
const clean=slug=>slug==='index'?'/':`/${slug}/`;
for(const [from,to] of Object.entries(redirects)){if(pages.some(p=>clean(p.slug)===from))throw Error('Redirect overschrijft bestaande pagina: '+from);if(!pages.some(p=>clean(p.slug)===to))throw Error('Redirectdoel bestaat niet: '+to);}
const nav=[['diensten','Diensten'],['landen','Landen'],['kwaliteit','Kwaliteit'],['over-ons','Over ons'],['kennisbank','Kennisbank'],['contact','Contact']];
const footerLinks=items=>items.map(([slug,title])=>`<a href="${slug}.html">${title}</a>`).join('');
const footer=`<footer class="footer"><div class="container"><div class="footer-grid"><div><div class="logo-foot"><img src="${site.logo}" width="48" height="48" loading="lazy" alt=""><strong>${esc(site.name)}</strong></div><p>Internationaal koel- en vriestransport.<br>Direct contact, duidelijke afspraken.</p><p>KvK ${esc(site.kvk)}<br>BTW ${esc(site.vat)}</p></div><div><h2>Diensten</h2><div class="footer-links">${footerLinks([['koeltransport','Koeltransport'],['vriestransport','Vriestransport'],['geconditioneerd-transport','Geconditioneerd transport'],['internationaal-koeltransport','Internationaal koeltransport'],['internationaal-vriestransport','Internationaal vriestransport'],['groupage-koeltransport','Groupage'],['food-transport','Food en levensmiddelen']])}</div></div><div><h2>OKT Logistics</h2><div class="footer-links">${footerLinks([['koeltransport-duitsland','Duitsland'],['koeltransport-belgie','België'],['koeltransport-frankrijk','Frankrijk'],['kwaliteit','Kwaliteit'],['over-ons','Over ons'],['kennisbank','Kennisbank'],['algemene-voorwaarden','Algemene voorwaarden'],['privacy','Privacy'],['cookies','Cookies']])}<button type="button" data-cookie-open>Cookievoorkeur</button></div></div><div><h2>Contact</h2><p>${esc(site.address)}<br>${esc(site.postcode)} ${esc(site.city)}</p><p><a href="tel:${site.phone.replace(/ /g,'')}">${esc(site.phone)}</a><br><a href="tel:${site.office.replace(/ /g,'')}">${esc(site.office)}</a></p><a href="mailto:${site.email}">${esc(site.email)}</a></div></div><div class="copy">© ${new Date().getFullYear()} ${esc(site.name)}</div></div></footer>`;
function form(id){
const fields=[['company','Bedrijfsnaam','text',true,'organization'],['name','Contactpersoon','text',true,'name'],['email','E-mail','email',true,'email'],['phone','Telefoon','tel',false,'tel'],['pickup','Laadplaats en land','text',true,'off'],['delivery','Losplaats en land','text',true,'off'],['loadDate','Laaddatum','date',true,'off'],['unloadDate','Losdatum / tijdvenster','text',false,'off'],['temperature','Gewenste temperatuur','text',true,'off'],['pallets','Aantal pallets','number',false,'off'],['weight','Totaalgewicht in kg','number',false,'off'],['goods','Type goederen','text',true,'off']];
return `<form class="quote-form form-panel" data-quote-form><p>Velden met * zijn verplicht.</p><div class="field-grid">${fields.map(([name,label,type,required,auto])=>`<div class="form-row"><label for="${id}-${name}">${label}${required?' *':''}</label><input id="${id}-${name}" name="${name}" type="${type}" ${required?'required':''} autocomplete="${auto}" ${type==='number'?'min="1" max="1000000" step="1"':'maxlength="160"'}></div>`).join('')}<div class="form-row"><label for="${id}-mode">Transportvorm *</label><select id="${id}-mode" name="mode" required><option value="">Kies een optie</option><option>FTL / complete vracht</option><option>Groupage / deellading</option><option>Graag advies</option></select></div></div><div class="form-row"><label for="${id}-message">Opmerking</label><textarea id="${id}-message" name="message" maxlength="3000" placeholder="Tijdvensters, referenties, palletmaten of andere bijzonderheden"></textarea></div><div class="hp" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><p class="form-note">Gebruik uw zakelijke contactgegevens. Een aanvraag is nog geen bevestigde boeking. <a href="privacy.html">Privacy-informatie</a> · <a href="algemene-voorwaarden.html">Algemene voorwaarden</a>.</p><p class="form-status" role="status" aria-live="polite">U kunt uw ingevulde aanvraag per e-mail opstellen.</p><div class="form-actions"><button class="btn btn-blue" type="submit">Aanvraag per e-mail opstellen</button><button class="btn btn-secondary" type="button" data-download>Aanvraag downloaden</button></div><noscript><p>Neem rechtstreeks contact op via <a href="mailto:${site.email}">${site.email}</a> of bel ${esc(site.phone)}.</p></noscript></form>`;
}
for(const p of pages){
const url=site.domain+clean(p.slug);
const shareImage=p.main.match(/<img[^>]*src="([^"]+)"/)?.[1]||'assets/okt-truck-v10-1280.webp';
const shareAlt=p.main.match(/<img[^>]*alt="([^"]*)"/)?.[1]||'OKT Logistics truck';
let main=p.main.replace(/<div data-component="quote-form"><\/div>/g,()=>form(`q-${p.slug}`));
// Strengthen breadcrumb semantics without rebuilding page-specific compositions.
main=main.replace(/<div class="breadcrumbs">([\s\S]*?)<\/div>/g,(_,s)=>`<nav class="breadcrumbs" aria-label="Broodkruimel">${s.replace(/^\s*Home\s*\//,'<a href="index.html">Home</a> /')}</nav>`);
const heading=main.match(/<h1[^>]*>([\s\S]*?)<\/h1>/)?.[1].replace(/<[^>]+>/g,'')||p.title;
const pageLabel=p.title.split('|')[0].trim();
const parent=p.type==='article'?['kennisbank','Kennisbank']:p.slug.startsWith('koeltransport-')&&['koeltransport-duitsland','koeltransport-belgie','koeltransport-frankrijk'].includes(p.slug)?['landen','Landen']:p.type==='service'?['diensten','Diensten']:null;
const crumbs=[{name:'Home',url:site.domain+'/'}];if(parent)crumbs.push({name:parent[1],url:site.domain+clean(parent[0])});crumbs.push({name:pageLabel,url});
if(p.slug!=='index'&&!['hidden'].includes(p.type)){
 const crumbHtml=`<nav class="breadcrumbs" aria-label="Broodkruimel"><a href="index.html">Home</a> / ${parent?`<a href="${parent[0]}.html">${parent[1]}</a> / `:''}<span aria-current="page">${esc(pageLabel)}</span></nav>`;
 if(main.includes('class="breadcrumbs"'))main=main.replace(/<nav class="breadcrumbs"[^>]*>[\s\S]*?<\/nav>/,crumbHtml);
 else main=main.replace(/(<section[^>]*>\s*<div class="container">)/,'$1'+crumbHtml);
}
let schema=[{'@context':'https://schema.org','@type':'Organization','@id':site.domain+'/#organization',name:site.name,url:site.domain,logo:site.domain+'/'+site.logo,email:site.email,telephone:site.phone,address:{'@type':'PostalAddress',streetAddress:site.address,postalCode:site.postcode,addressLocality:site.city,addressCountry:'NL'}}];
schema[0].legalName=site.name;
schema[0].areaServed=['Nederland','Duitsland','België','Frankrijk'].map(name=>({'@type':'Country',name}));
schema[0].knowsAbout=['Koeltransport','Vriestransport','Geconditioneerd transport','Groupage','Food transport'];
schema[0].vatID=site.vat;
schema[0].contactPoint={'@type':'ContactPoint',contactType:'Transportaanvragen',email:site.email,telephone:site.phone};
if(p.slug==='index'){schema[0].hasOfferCatalog={'@type':'OfferCatalog',name:'Transportdiensten',itemListElement:pages.filter(v=>v.type==='service').map(v=>({'@type':'Offer',itemOffered:{'@type':'Service','@id':site.domain+clean(v.slug)+'#service',name:v.title.split('|')[0].trim(),url:site.domain+clean(v.slug),provider:{'@id':site.domain+'/#organization'}}}))};schema.push({'@context':'https://schema.org','@type':'WebSite','@id':site.domain+'/#website',url:site.domain+'/',name:site.name,inLanguage:'nl-NL',publisher:{'@id':site.domain+'/#organization'}});}
if(p.slug!=='index'&&!['hidden','draft'].includes(p.type))schema.push({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:crumbs.map((c,i)=>({'@type':'ListItem',position:i+1,name:c.name,item:c.url}))});
if(p.type==='article')schema.push({'@context':'https://schema.org','@type':'Article',...(p.lastModified?{dateModified:p.lastModified}:{}),...(p.datePublished?{datePublished:p.datePublished}:{}),headline:heading,description:p.description,mainEntityOfPage:url,author:{'@type':'Organization',name:site.name},publisher:{'@id':site.domain+'/#organization'},image:site.domain+'/'+shareImage,inLanguage:'nl-NL'});
if(p.type==='service')schema.push({'@context':'https://schema.org','@type':'Service','@id':url+'#service',serviceType:pageLabel,name:heading,description:p.description,url,provider:{'@id':site.domain+'/#organization'},areaServed:['Nederland','Duitsland','België','Frankrijk']});
const header=`<a class="skip-link" href="#main">Naar inhoud</a><div class="topbar"><div class="container"><span>Nederland · Duitsland · België · Frankrijk</span><a href="tel:${site.phone.replace(/ /g,'')}">${esc(site.phone)}</a></div></div><header class="header"><div class="container nav"><a class="brand" href="index.html" aria-label="OKT Logistics — homepage"><img src="${site.logo}" width="44" height="44" alt=""><span><span class="name">OKT Logistics</span><span class="sub">Koel- en vriestransport</span></span></a><button class="menu-toggle" type="button" aria-controls="main-nav" aria-expanded="false">Menu <span aria-hidden="true">☰</span></button><nav class="navlinks" id="main-nav" aria-label="Hoofdnavigatie">${nav.map(([slug,label])=>`<a href="${slug}.html" ${slug===p.slug?'aria-current="page"':''}>${label}</a>`).join('')}<a class="btn btn-blue" href="contact.html">Offerte aanvragen</a></nav></div></header>`;
main=main.replace('<main>','<main id="main" tabindex="-1">');
const html=`<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(p.title)}</title><meta name="description" content="${esc(p.description)}">${['hidden','draft'].includes(p.type)?'<meta name="robots" content="noindex,follow">':''}<link rel="canonical" href="${url}"><meta property="og:title" content="${esc(p.title)}"><meta property="og:description" content="${esc(p.description)}"><meta property="og:type" content="${p.type==='article'?'article':'website'}"><meta property="og:url" content="${url}"><meta property="og:site_name" content="${esc(site.name)}"><meta property="og:locale" content="nl_NL"><meta property="og:image" content="${site.domain}/${shareImage}"><meta property="og:image:alt" content="${esc(shareAlt)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(p.title)}"><meta name="twitter:description" content="${esc(p.description)}"><meta name="twitter:image" content="${site.domain}/${shareImage}"><meta name="twitter:image:alt" content="${esc(shareAlt)}"><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="style.css"><link rel="stylesheet" href="improvements.css"><script type="application/ld+json">${j(schema)}</script><script src="site.js" defer></script></head><body>${header}${main}${footer}<dialog id="cookie-dialog" aria-labelledby="cookie-heading"><h2 id="cookie-heading">Uw privacykeuze</h2><p>Functionele opslag is nodig om uw keuze te onthouden. Statistieken worden alleen geladen als u die toestaat én als ze zijn ingesteld.</p><p><a href="cookies.html">Meer over cookies</a></p><div class="form-actions"><button type="button" class="btn btn-secondary" data-cookie="essential">Alleen noodzakelijk</button><button type="button" class="btn btn-blue" data-cookie="analytics">Statistieken toestaan</button><button type="button" class="btn btn-secondary" data-cookie-close>Sluiten</button></div></dialog></body></html>`;
const versioned=html.replace(/(href|src)="(style\.css|improvements\.css|site\.js)"/g,(_,attr,file)=>`${attr}="${file}?v=${crypto.createHash('sha256').update(fs.readFileSync(path.join(pub,file))).digest('hex').slice(0,12)}"`);
fs.writeFileSync(path.join(pub,p.slug+'.html'),versioned);
}
for(const [from,to] of Object.entries(redirects)){
const slug=from.replace(/^\/|\/$/g,'');if(!slug||pages.some(p=>p.slug===slug))continue;
const target=to==='/'?'index':to.replace(/^\/|\/$/g,'');
fs.writeFileSync(path.join(pub,slug+'.html'),`<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="robots" content="noindex,follow"><meta http-equiv="refresh" content="0;url=${target}.html"><link rel="canonical" href="${site.domain}${to}"><title>Pagina verplaatst | OKT Logistics</title></head><body><p>Deze informatie staat op <a href="${target}.html">de bijgewerkte pagina</a>.</p></body></html>`);
}
fs.writeFileSync(path.join(pub,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+pages.filter(p=>!['hidden','draft'].includes(p.type)).map(p=>`<url><loc>${esc(site.domain+clean(p.slug))}</loc>${p.lastModified?`<lastmod>${p.lastModified}</lastmod>`:''}</url>`).join('')+'</urlset>');
fs.writeFileSync(path.join(pub,'robots.txt'),`User-agent: *\nAllow: /\nDisallow: /api/\nSitemap: ${site.domain}/sitemap.xml\n`);
fs.writeFileSync(path.join(pub,'favicon.svg'),'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#243E85"/><text x="32" y="41" text-anchor="middle" font-family="Arial,sans-serif" font-size="25" font-weight="bold" fill="white">OKT</text></svg>');
return pages.length;
}
if(process.argv[1]===fileURLToPath(import.meta.url))console.log(`Built ${build()} pages.`);
